### Array concatenation, splitting and stacking

There are two ways of combining several arrays into one bigger array:
1. concatenate and
2. stack.

`Concatenate` takes n-dimensional arrays and returns an n-dimensional array, whereas `stack` takes n-dimensional arrays and returns n+1-dimensional array. Few examples of these:

In [1]:
import numpy as np

In [31]:
a=np.arange(2)
b=np.arange(2,5)

In [32]:
print(f'a has shape {a.shape}: {a}')
print(f'b has shape {b.shape}: {b}')

a has shape (2,): [0 1]
b has shape (3,): [2 3 4]


In [33]:
np.concatenate((a,b))  # concatenating 1-D arrays

array([0, 1, 2, 3, 4])

In [20]:
c=np.arange(1,5).reshape(2,2)
print(f'c has shape {c.shape}: {c}', sep='\n')
d= np.concatenate((c,c))  # concatenating 2-D arrays
print(f'd has shape {d.shape}: {d}', sep='\n')

c has shape (2, 2): [[1 2]
 [3 4]]
d has shape (4, 2): [[1 2]
 [3 4]
 [1 2]
 [3 4]]


By default concatenate joins the arrays along axis 0. To join the arrays horizontally, add parameter `axis=1`:

<img src="images/image1.png" wideth=1000>

In [23]:
e=np.concatenate((c,c), axis=1)
print(f'e has shape {e.shape}: {e}', sep='\n')

e has shape (2, 4): [[1 2 1 2]
 [3 4 3 4]]


If you want to catenate arrays with different dimensions, for example to add a new column to a 2d array, you must first reshape the arrays to have same number of dimensions:

In [24]:
print('New row')
print(np.concatenate((c, a.reshape(1,2))))

New row
[[1 2]
 [3 4]
 [0 1]]


In [26]:
print('New column')
print(np.concatenate((c, a.reshape()), axis=1))

New column
[[1 2 0]
 [3 4 1]]


Use `stack` to create higher dimensional arrays from lower dimensional arrays:

In [35]:
print(np.stack((b,b)))

[[2 3 4]
 [2 3 4]]


In [36]:
print(np.stack((b,b), axis=1))

[[2 2]
 [3 3]
 [4 4]]


Inverse operation of concatenate is `split`. Its argument specifies either

1. the number of equal parts the array is divided into, or
2. it specifies explicitly the break points.

In [39]:
d=np.arange(12).reshape(6,2)
print('d:\n', d)
d1,d2=np.split(d,2)
print('d1:\n', d1)
print('d2:\n', d2)


d:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
d1:
 [[0 1]
 [2 3]
 [4 5]]
d2:
 [[ 6  7]
 [ 8  9]
 [10 11]]


In [41]:
d=np.arange(12).reshape(2,6)
print('d:\n', d)
parts= np.split(d, (2,3,5), axis=1)
for i, p in enumerate(parts):
    print(f'part {i}\n {p}')


d:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
part 0
 [[0 1]
 [6 7]]
part 1
 [[2]
 [8]]
part 2
 [[ 3  4]
 [ 9 10]]
part 3
 [[ 5]
 [11]]
