<img src="images/image2.png" wisth=600>

In [1]:
import numpy as np

In [3]:
a=np.array([
    [5,0,3],
    [3,7,9]
])
'''
aᵀ = ([
   [5,3],
    [0,7],
    [3,9]
])
'''


In [29]:
for b in list(a):
    print(np.array(b)[np.newaxis,:])

[[5 0 3]]
[[3 7 9]]


In [31]:
[np.array(b)[np.newaxis,:] for b in list(a)]

[array([[5, 0, 3]]), array([[3, 7, 9]])]

In [33]:
[np.array(b)[:,np.newaxis] for b in list(a.T)]

[array([[5],
        [3]]),
 array([[0],
        [7]]),
 array([[3],
        [9]])]

In [ ]:
import numpy as np

def get_row_vectors(a):
    return [np.array(b)[np.newaxis,:] for b in list(a)]

def get_column_vectors(a):
    return [np.array(b)[:,np.newaxis] for b in list(a.T)]

def main():
    np.random.seed(0)
    a=np.random.randint(0,10, (4,4))
    print("a:", a)
    print("Row vectors:", get_row_vectors(a))
    print("Column vectors:", get_column_vectors(a))

if __name__ == "__main__":
    main()
