### Aggregations: max, min, sum, mean, standard deviation and more

Aggregations allow us to condense the information in an array into just few numbers

In [1]:
import numpy as np

In [3]:
np.random.seed(0)
a=np.random.randint(-100,100,(4,5))
print(a)

[[ 72 -53  17  92 -33]
 [ 95   3 -91 -79 -64]
 [-13 -30 -12  40 -42]
 [ 93 -61 -13  74 -12]]


In [6]:
print(f'Minimum: {a.min()}, Maximum: {a.max()} ')
print(f'Sum: {a.sum()}')
print(f'Mean: {a.mean()}, standard deviation: {a.std()}')

Minimum: -91, Maximum: 95 
Sum: -17
Mean: -0.85, standard deviation: 58.39886557117355


Instead of aggregating over the whole array, we can aggregate over certain axes only as well:

<img src="images/image1.png" width=1000>

In [10]:
np.random.seed(9)
b=np.random.randint(0,10,(3,4))
print(b)
print(f'Column sums: {b.sum(axis=0)}')
print(f'Row sums: {b.sum(axis=1)}')

[[5 6 8 6]
 [1 6 4 8]
 [1 8 5 1]]
Column sums: [ 7 20 17 15]
Row sums: [25 19 15]


Let's measure how much slower Python's sum function is compared to NumPy's equivalent when aggregating over an array:

In [15]:
a=np.arange(1000) #creates a 1D NumPy array containing 1,000 sequential integers starting from 0 up to 999.
print(a.ndim)

1


In [16]:
%timeit np.sum(a)

722 ns ± 9.96 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [17]:
%timeit sum(a)

26.2 μs ± 1.57 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


The speed of NumPy is partly due to the fact that its arrays must have same type for all the elements. This requirement allows some efficient optimizations.