### Fast computation using universal functions

In [2]:
import numpy as np

In addition to providing a way to store and access multi-dimension arrays, NumPy also provides several routines to perform computations on them. One of the reasons for the popularity of NumPy is that these computations can be very efficient, much more efficient than what Python can normally do. The biggest bottle-necks in efficiency are the loops, which can be iterated millions, billions, or even more times. The loops should be as efficient as possible. What slows down loops in Python is the fact that Python is a dynamically typed language. This means that at each expression Python has to find out the types of the arguments of the operations. Let's consider the following loop:

In [1]:
L=[1,5.2,'ab']
L2=[]
for x in L:
    L2.append(x*2)
print(L2)

[2, 10.4, 'abab']


At each iteration of this loop Python has to find out the type of the variable x, which can in this example be an int, a float or a string, and depending on this type call a different function to perform the "multiplication" by two. What makes NumPy efficient, is the requirement that each element in an array must be of the same type. This homogeneity of arrays makes it possible to create `vectorized` operation, which don't operate on single elements, but on arrays (or subarrays). The previous example using vectorized operations of NumPy is shown below.

In [7]:
a=np.array([2.1,5.0,17.2])
a2=a*2
print(a2)

[ 4.2 10.  34.4]


## "Vectorized" — Simply

**Vectorized** means an operation applies to a **whole array at once** — in a single step — instead of you writing a loop that processes one element at a time. NumPy does the looping internally, in fast low-level code, rather than in slow Python.

---

### The Contrast — Loop vs Vectorized

**The slow way — an explicit Python loop:**

```python
data = [1, 2, 3, 4, 5]
result = []
for x in data:
    result.append(x * 2)      # one element at a time
# → [2, 4, 6, 8, 10]
```

**The vectorized way — operate on the whole array at once:**

```python
import numpy as np
data = np.array([1, 2, 3, 4, 5])
result = data * 2             # NO loop! the whole array, in one operation
# → array([2, 4, 6, 8, 10])
```

`data * 2` doesn't multiply just one number — it multiplies **every element simultaneously**, with no `for` loop written by you. That's "vectorized": the operation is expressed on the **vector (array) as a whole**, not element by element.

---

### Why the Passage Mentions "Type Checking"

The passage explains **why** the loop version is slow. In a plain Python loop:

```python
for x in data:
    x * 2
```

**Every single iteration**, Python must stop and ask: *"what type is `x` this time — int? float? string?"* — because Python variables can be any type (dynamic typing, remember). Only after checking does it pick the right "multiply" behavior. That per-element type check, repeated millions of times, is **expensive**.

```
Loop, each iteration:  check type of x → pick right multiply → do it → repeat
                       └────── this checking happens EVERY element ──────┘
```

---

### Why NumPy Avoids That Cost — Homogeneity

The passage's key point: **every element in a NumPy array is the same type** (all int64, or all float64, etc.). Because of this guarantee:

```
NumPy already KNOWS every element is (say) int64.
→ No need to check the type element-by-element.
→ It can run ONE tight, pre-compiled loop in C, applying the SAME operation to all.
```

Since the type is uniform and known upfront, NumPy skips the repeated "what type is this?" question entirely, and runs the multiplication in fast, low-level machine code over the whole array — that's what makes vectorized operations dramatically faster than a Python loop.

---

### The Speed Difference Is Real

```python
# Python loop over a million numbers — slow (type-checks each one)
result = [x * 2 for x in range(1_000_000)]

# NumPy vectorized — often 10–100× faster
arr = np.arange(1_000_000)
result = arr * 2
```

Same answer, but the vectorized version does the work in one compiled sweep instead of a million separate Python-level type-checked steps.

---

### Vectorized Operations Work for Lots of Things

```python
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

a + b        # → [11, 22, 33, 44]    element-wise addition, whole arrays
a * b         # → [10, 40, 90, 160]   element-wise multiplication
a ** 2         # → [1, 4, 9, 16]        square every element
a > 2           # → [False, False, True, True]   compare every element
np.sqrt(a)       # → [1.0, 1.41, 1.73, 2.0]   square-root every element
```

**None of these need a `for` loop** — each operates on the entire array at once. That's the vectorized style.

---

### The Mental Shift

```
Regular Python thinking:  "loop through, do something to each element"
Vectorized NumPy thinking: "apply the operation to the whole array as one unit"
```

You stop thinking element-by-element and start thinking array-at-a-time — which is both **shorter to write** and **much faster to run**.

---

### The One-Sentence Summary

> **Vectorized** means an operation is applied to an **entire array in a single step** (like `arr * 2`), instead of looping element by element — and it's fast specifically because NumPy arrays are **homogeneous** (every element the same type), so NumPy can skip Python's per-element "what type is this?" check and run one tight, pre-compiled loop over all elements at once. You write no loop yourself; NumPy does the iteration internally in fast low-level code. 🎯

Because each iteration is using identical operations only the data differs, this can be compiled into machine language, and then performed in one go, hence avoiding Python's dynamic typing. The name vector operation comes from linear algebra where the addition of two vectors `v=(v1,v2,…,vd)` and `w=(w1,w2,…,wd)` is defined element-wise as `v+w=(v1+w1,v2+w2,…,vd+wd)`.

In addition to addition there are several mathematical functions defined in the vector form. The basic arithmetic operations are:

<img src="images/image1.png" width=600>

They can be combined into more complicated expressions. An example:

In [9]:
b=np.array([-1,3.2,2.4])
print(-a**2 * b)

[   4.41   -80.    -710.016]


Several other mathematical functions are defined as well. A few examples of these can be found below.

In [10]:
print(np.abs(b))
print(np.cos(b))
print(np.exp(b))
print(np.log2(np.abs(b)))

[1.  3.2 2.4]
[ 0.54030231 -0.99829478 -0.73739372]
[ 0.36787944 24.5325302  11.02317638]
[0.         1.67807191 1.26303441]


In NumPy nomenclature these vector operations are called ufuncs (universal functions).

## Four NumPy Math Functions — Simply

All four are **vectorized** functions (from the concept you just learned) — each applies its math operation to **every element** of the array at once, no loop needed. Let me explain what each one computes.

---

### Setup — Let's Use a Concrete Example

```python
import numpy as np
b = np.array([-2, 0, 3])
```

---

### 1. `np.abs(b)` — Absolute Value

Removes the sign — turns negatives into positives, leaves positives alone:

```python
np.abs(b)     # → array([2, 0, 3])
```

```
-2 → 2      (sign removed)
 0 → 0
 3 → 3      (already positive)
```

Same as the math `|x|` you know — applied to every element. This is the vectorized version of Python's built-in `abs()`.

---

### 2. `np.cos(b)` — Cosine (Trigonometry)

Computes the cosine of each element (treating them as **radians**, not degrees):

```python
np.cos(b)     # → array([-0.416,  1.   , -0.99 ])
```

```
cos(-2) → -0.416
cos(0)  →  1.0      (cosine of 0 is always 1)
cos(3)  → -0.99
```

The trig cosine function from math class, applied element-wise. (Related functions: `np.sin`, `np.tan`.)

---

### 3. `np.exp(b)` — Exponential (e raised to the power)

Computes $e^x$ for each element, where $e \approx 2.718$ (Euler's number):

```python
np.exp(b)     # → array([0.135, 1.   , 20.086])
```

```
e^(-2) → 0.135
e^(0)  → 1.0        (anything to the power 0... well, e^0 = 1)
e^(3)  → 20.086
```

This is the **exponential function** — the inverse of the natural logarithm. Grows very fast for positive numbers, shrinks toward 0 for negative ones.

---

### 4. `np.log2(np.abs(b))` — Base-2 Logarithm of the Absolute Value

This one is **nested** — two operations, inside-out (like your regex/function-nesting lessons):

**Inner: `np.abs(b)` first** — take absolute values (so there are no negatives):
```python
np.abs([-2, 0, 3])    # → [2, 0, 3]
```

**Outer: `np.log2(...)`** — base-2 logarithm of each result:
```python
np.log2([2, 0, 3])    # → [1.0, -inf, 1.585]
```

```
log2(2) → 1.0        (2 = 2¹, so log base 2 is 1)
log2(0) → -inf       ⚠ log of 0 is undefined → negative infinity + a warning
log2(3) → 1.585
```

**Why `np.abs` is applied first:** logarithms are **undefined for negative numbers** — `log2(-2)` would produce `nan` (not-a-number) and a warning. Wrapping `b` in `np.abs` first guarantees all inputs are non-negative, avoiding that problem. (Though `0` still gives `-inf`, since log of zero is also undefined — worth being aware of.)

`log2(x)` answers: *"2 to what power gives x?"* — so `log2(8) = 3` because $2^3 = 8$.

---

### The Common Thread — All Vectorized

The key point connecting all four: **none of them need a loop.** Each applies its operation to the **entire array simultaneously**:

```python
np.abs(b)       # abs of EVERY element at once
np.cos(b)        # cos of EVERY element at once
np.exp(b)         # e^x for EVERY element at once
np.log2(...)       # log2 of EVERY element at once
```

Compare to plain Python, where you'd need `[abs(x) for x in b]` or a `for` loop — NumPy does it in one fast, vectorized sweep.

---

### Summary Table

| Function | Computes | Example: input `3` → |
|---|---|---|
| `np.abs(b)` | absolute value \|x\| | `3` |
| `np.cos(b)` | cosine (radians) | `-0.99` |
| `np.exp(b)` | $e^x$ (exponential) | `20.086` |
| `np.log2(np.abs(b))` | base-2 log of \|x\| | `1.585` |

---

### The One-Sentence Summary

> These are four **vectorized** NumPy math functions, each applying its operation to every array element at once: `np.abs` strips the sign (absolute value), `np.cos` computes cosine (in radians), `np.exp` computes $e^x$ (exponential), and `np.log2(np.abs(b))` takes the base-2 logarithm after first making everything non-negative with `np.abs` (since logarithms are undefined for negative numbers). All four replace what would otherwise be an element-by-element loop with a single fast operation on the whole array. 🎯