<img src="images/image2.png" width=600>

In [1]:
import numpy as np

In [46]:
I=np.eye(2,2, dtype='int')
print(I)

[[1 0]
 [0 1]]


In [47]:
x=np.fliplr(I)
print(x)


[[0 1]
 [1 0]]


In [48]:
print(x[1:,:])

[[1 0]]


In [49]:
c1=np.concatenate((I,x[1:,:]))
print(c1)

[[1 0]
 [0 1]
 [1 0]]


In [50]:
c2=np.fliplr(c1)
print(c2)

[[0 1]
 [1 0]
 [0 1]]


In [51]:
c=np.concatenate( (c2, c1[:,1:]), axis=1 )
print(c)

[[0 1 0]
 [1 0 1]
 [0 1 0]]


In [57]:
def diamond(n):
    """
    Create a diamond-shaped pattern of 1s in a 2D numpy array of size (2n-1) x (2n-1).
    The diamond is formed by combining an identity matrix and its mirrored version.
    """
    I=np.eye(n, dtype='int')
    I_mirrored=np.fliplr(I)
    top_half=np.concatenate((I,I_mirrored[1:,:]))
    left_half=np.fliplr(top_half)
    full=np.concatenate( (left_half, top_half[:,1:]), axis=1 )
    print(full)

In [58]:
diamond(1)

[[1]]


In [ ]:
def diamond(n):
    """Return a (2n-1)x(2n-1) integer array whose 1s form a diamond outline.

    Built from an n x n identity matrix (one quarter of the diamond):
    concatenate it with its vertical mirror to make the top-and-bottom half,
    then concatenate that with its horizontal mirror to complete the shape.
    Overlapping middle row/column are removed by slicing so they aren't doubled.
    """
    quarter = np.eye(n, dtype=int)                            # a diagonal — one arm of the diamond
    half = np.concatenate((quarter, np.fliplr(quarter)[1:, :]))   # stack vertically (drop shared row)
    return np.concatenate((np.fliplr(half)[:, :-1], half), axis=1)  # mirror left (drop shared col)