### Sorting arrays

In [1]:
import numpy as np

In [2]:
a=np.array([2,1,4,3,5])
print(np.sort(a))  #Does not modify the argument
print(a)

[1 2 3 4 5]
[2 1 4 3 5]


In [4]:
a.sort() # Modifies the argument
print(a)

[1 2 3 4 5]


In [6]:
b=np.random.randint(0,10,(4,4))
print(b)

[[2 8 6 5]
 [4 0 8 8]
 [7 3 9 2]
 [7 5 9 8]]


In [8]:
np.sort(b, axis=0)  # sort each column

array([[2, 0, 6, 2],
       [4, 3, 8, 5],
       [7, 5, 9, 8],
       [7, 8, 9, 8]])

In [9]:
np.sort(b,axis=1)

array([[2, 5, 6, 8],
       [0, 4, 8, 8],
       [2, 3, 7, 9],
       [5, 7, 8, 9]])

Note that each row or column is sorted independently.

A related operation is the `argsort` function. Which doesn't sort the elements, but returns the indices of the sorted elements. An example will demonstrate this:

In [10]:
a=np.array([23,12,47,35,59])
print('Array a : ', a)
idx = np.argsort(a)
print('Indices:', idx)

Array a :  [23 12 47 35 59]
Indices: [1 0 3 2 4]


These indices say that the smallest element of the array is in position 1 of `a`, second smallest elements is in position 0 of `a`, third smallest is in position 3, and so on. We can verify that these indices will indeed order the elements using fancy indexing:

In [11]:
print(a[idx])

[12 23 35 47 59]
