In [1]:
import numpy as np

In [2]:
a = np.array(
 [[5, 0, 3, 3, 7, 9, 3, 5, 2, 4],
 [7, 6, 8, 8, 1, 6, 7, 7, 8, 1],
 [5, 9, 8, 9, 4, 3, 0, 3, 5, 0],
 [2, 3, 8, 1, 3, 3, 3, 7, 0, 1],
 [9, 9, 0, 4, 7, 3, 2, 7, 2, 0],
 [0, 4, 5, 5, 6, 8, 4, 1, 4, 9],
 [8, 1, 1, 7, 9, 9, 3, 6, 7, 2],
 [0, 3, 5, 9, 4, 4, 6, 4, 4, 3],
 [4, 4, 8, 4, 3, 7, 5, 5, 0, 1],
 [5, 9, 3, 0, 5, 0, 1, 2, 4, 2]])

In [7]:
np.sort(a[:,-1])

array([0, 0, 1, 1, 1, 2, 2, 3, 4, 9])

In [8]:
from collections import Counter

last = a[:, -1]                                    # extract the last column
counts = Counter(last.tolist())                     # count each value's occurrences
sorted_col = sorted(last.tolist(), key=lambda x: -counts[x])   # most frequent first

In [9]:
print(sorted_col)

[1, 1, 1, 0, 0, 2, 2, 4, 9, 3]


In [13]:

freq = np.array([counts[x] for x in last])       # each row's last-value frequency
order = np.argsort(-freq, kind='stable')         # row order (most frequent first)
result = a[order]                                 # reorder ALL rows


In [14]:
print(result)

[[7 6 8 8 1 6 7 7 8 1]
 [2 3 8 1 3 3 3 7 0 1]
 [4 4 8 4 3 7 5 5 0 1]
 [5 9 8 9 4 3 0 3 5 0]
 [9 9 0 4 7 3 2 7 2 0]
 [8 1 1 7 9 9 3 6 7 2]
 [5 9 3 0 5 0 1 2 4 2]
 [5 0 3 3 7 9 3 5 2 4]
 [0 4 5 5 6 8 4 1 4 9]
 [0 3 5 9 4 4 6 4 4 3]]
