### Array types and attributes

An array has several attributes:

1. ```ndim``` tells the number of dimensions,
2. ```shape``` tells the size in each dimension,
3. ```size``` tells the number of elements, and
4. ```dtype``` tells the element type.

Let's create a helper function to explore these attributes:

In [1]:
import numpy as np

In [3]:
def info(name, a):
    print(f'{name} has dim {a.ndim}, shape {a.shape}, size {a.size} and dtype {a.dtype}')
    print(a)

In [5]:
b=np.array([
    [1,2,3],
    [4,5,6]
])

info('b',b)

b has dim 2, shape (2, 3), size 6 and dtype int64
[[1 2 3]
 [4 5 6]]


In [9]:
c=np.array([b,b])  # Create a 3-D array
info('c',c)

'''
2-D matrix
[1,2]
[3,4]
------------------
3-D matrix
c=[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]

c1=[
[1 2 3]
[4 5 6]
]

c2=[
[1 2 3]
[4 5 6]
]
'''

c has dim 3, shape (2, 2, 3), size 12 and dtype int64
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


'[\n[[1 2 3][4 5 6]],\n[[1 2 3][4 5 6]]\n]'

In [10]:
d=np.array([
    [1,2,3,4]            # a raw vector
])
info('d',d)

d has dim 2, shape (1, 4), size 4 and dtype int64
[[1 2 3 4]]


Note above how Python printed the three dimensional array. The general rules of printing an n-dimensional array as a nested list are:

- the last dimension is printed from left to right,
- the second-to-last is printed from top to bottom,
- the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

## How NumPy Prints Multi-Dimensional Arrays — Simply

These three rules describe **which direction each dimension "flows"** when NumPy displays an array as text. Let's decode them using your actual example.

---

### First — What "Dimensions" Mean Here

Your array `c` has **shape `(2, 2, 3)`** — three numbers, meaning three dimensions:

```
shape (2, 2, 3)
       │  │  │
       │  │  └── LAST dimension: 3 elements    → prints LEFT TO RIGHT
       │  └───── MIDDLE dimension: 2 elements   → prints TOP TO BOTTOM
       └──────── FIRST dimension: 2 elements     → prints as separated SLICES (blank line between)
```

Each rule in the text corresponds to one of these dimensions.

---

### Rule 1 — "The Last Dimension Is Printed Left to Right"

The **innermost/last** number in the shape (here, `3`) becomes a **horizontal row**:

```
[1 2 3]
 └─┬─┘
  3 elements, laid out LEFT → RIGHT
```

So `[1 2 3]` and `[4 5 6]` are each a "last dimension" — 3 values printed side by side, horizontally.

---

### Rule 2 — "The Second-to-Last Is Printed Top to Bottom"

The **middle** number (`2`) stacks those rows **vertically**:

```
[[1 2 3]      ← row 1
 [4 5 6]]      ← row 2
   │
   2 rows, stacked TOP → BOTTOM
```

So one "block" is 2 rows (middle dimension) each containing 3 numbers (last dimension) — a little 2×3 grid.

---

### Rule 3 — "The Rest... Separated by an Empty Line"

The **first** number (`2`) creates **separate blocks**, each divided by a **blank line**:

```
[[[1 2 3]        ← block 1 starts
  [4 5 6]]

 [[1 2 3]         ← block 2 starts (after the blank line!)
  [4 5 6]]]
      │
      2 blocks, separated by an EMPTY LINE
```

The blank line between the two `[[1 2 3] [4 5 6]]` grids is the visual signal that you've moved along the **first** dimension.

---

### Putting It All Together — Reading Your `c` Output

```
[[[1 2 3]        ┐
  [4 5 6]]       │ ← first BLOCK (2×3 grid)
                  ┘
                  ← blank line = moving along FIRST dimension
 [[1 2 3]        ┐
  [4 5 6]]]      │ ← second BLOCK (2×3 grid)
                  ┘
```

Reading it by the three rules:
- **Left→right:** each `[1 2 3]` — the 3 innermost values
- **Top→bottom:** the two rows within each block (`[1 2 3]` above `[4 5 6]`)
- **Blank-line-separated:** the two blocks themselves (the outermost dimension)

Count them back to the shape: 2 blocks × 2 rows × 3 values = **`(2, 2, 3)`**, matching `c`'s reported shape exactly.

---

### The Bracket-Counting Shortcut

An easy way to *see* the dimensions: **count the opening brackets `[` at the very start**:

```
[[[1 2 3]...      ← THREE opening brackets = 3 dimensions
 [[1 2 3 4]]      ← TWO opening brackets = 2 dimensions (your 'd' example)
 [1 2 3]           ← ONE opening bracket = 1 dimension
```

Each level of nesting = one dimension, and the rules above tell you which **direction** that level flows when printed.

---

### Why `d` Looks Different — Shape `(1, 4)`

```python
d = np.array([[1, 2, 3, 4]])     # shape (1, 4)
# → [[1 2 3 4]]
```

```
shape (1, 4)
       │  │
       │  └── last dim: 4 → LEFT TO RIGHT → "1 2 3 4"
       └───── first dim: 1 → TOP TO BOTTOM, but only 1 row, so just one line
```

Two opening brackets `[[` = 2 dimensions, but since the first dimension is just `1`, there's only a single row — which is why it looks like a simple "row vector."

---

### The One-Sentence Summary

> When NumPy prints a multi-dimensional array, each dimension "flows" in a specific direction: the **innermost/last** dimension spreads **horizontally** (left to right, `[1 2 3]`), the **middle** dimension stacks those rows **vertically** (top to bottom), and every **outer** dimension separates its blocks with **blank lines** — so by reading the horizontal rows, the vertical stacking, and the blank-line gaps, you can reconstruct the array's exact shape (and counting the opening `[` brackets tells you how many dimensions there are). 🎯

Can you write the 3 dimensional matrix with mathematical notation

## Representing a 3D Array in Mathematical Notation

Let's take your exact example — the array `c` with shape `(2, 2, 3)` — and write it the way mathematics would.

A 3D array is a stack of 2D matrices. Your array c has shape `(2, 2, 3)` — meaning 2 matrices, each being a 2×3 grid.

<image src="images/image1.png" width="1000">

<image src="images/image2.png" width="1000">
