### Matrix operations

The `*` operator in NumPy corresponds to the element-wise product of two arrays. However, very often we would like to use the matrix multiplication. As a reminder, if a and b are two matrices with shapes n×k and k×m respectively, then the matrix product of a and b is the matrix c with shape n×m, where

<img src="images/image1.png">

In [1]:
import numpy as np

In NumPy we can compute the matrix product using the `np.matmul` function or the `@` operator. An example of this:

In [2]:
np.random.seed(0)
a=np.random.randint(0,10,(3,2))
b=np.random.randint(0,10,(2,4))
print(a)
print(b)

[[5 0]
 [3 3]
 [7 9]]
[[3 5 2 4]
 [7 6 8 8]]


In [6]:
def info(name, a):
    print(f"{name} has dim {a.ndim}, shape {a.shape}, size {a.size}, and dtype {a.dtype}:")
    print(a)

In [7]:
c=np.matmul(a,b)
info('c',c)

c has dim 2, shape (3, 4), size 12, and dtype int64:
[[ 15  25  10  20]
 [ 30  33  30  36]
 [ 84  89  86 100]]


In [8]:
print(a@b) # This is more convenient when complex expression are used

[[ 15  25  10  20]
 [ 30  33  30  36]
 [ 84  89  86 100]]


So, matrices are just two dimensional arrays with the product defined differently from the element-wise product. Note that for the matrix product to be defined, the two matrices have to have compatible shapes. So the following would produce an error:

In [9]:
a@a

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

Let's test some basic identities that should hold for an invertible matrix https://en.wikipedia.org/wiki/Invertible_matrix:

In [13]:
s=np.array([
  [1,6,7],
  [7,8,1],
  [5,9,8]
])
print('Original matrix:', s , sep='\n')
s_inv=np.linalg.inv(s)
print('Inverted matrix:', s_inv, sep='\n')
print('Matrix production:', s@s_inv, sep='\n')  #This should be pretty clode to the identity matrix np.eye(3)
print('Matric product the other way:', s_inv@s, sep='\n')  # same here


Original matrix:
[[1 6 7]
 [7 8 1]
 [5 9 8]]
Inverted matrix:
[[-0.61111111 -0.16666667  0.55555556]
 [ 0.56666667  0.3        -0.53333333]
 [-0.25555556 -0.23333333  0.37777778]]
Matrix production:
[[ 1.00000000e+00 -2.77555756e-17  3.33066907e-16]
 [ 7.21644966e-16  1.00000000e+00  1.11022302e-16]
 [ 0.00000000e+00 -2.22044605e-16  1.00000000e+00]]
Matric product the other way:
[[ 1.00000000e+00 -5.55111512e-16  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00  8.88178420e-16]
 [ 1.11022302e-16 -3.33066907e-16  1.00000000e+00]]


Let's try mapping a vector with the matrix and its inverse:

In [17]:
print(s)
x=np.array([1,4,2])
y=s@x
print(y)
print(s_inv@y)

[[1 6 7]
 [7 8 1]
 [5 9 8]]
[39 41 57]
[1. 4. 2.]
