### Fancy indexing

Using indexing we can get a single element from an array. If we wanted multiple (not necessarily contiguous -අනිවාර්යයෙන්ම එකිනෙක යාබද නොවන) elements, we would have to index several times:

In [1]:
import numpy as np

In [4]:
np.random.seed(0)
a=np.random.randint(0,20,20)
a2=np.array(
    [a[2],a[5],a[7]]
)
print(a)
print(a2)

[12 15  0  3  3  7  9 19 18  4  6 12  1  6  7 14 17  5 13  8]
[ 0  7 19]


That's quite verbose. Fancy indexing provides a concise syntax for accessing multiple elements:

In [6]:
idx = [2,5,7] # List of indices
print(a[idx]) # In fancy indexing in place of a single index, we can provide a list of indices ('Fancy indexing' හිදී, තනි දර්ශකයක් (index) වෙනුවට දර්ශක ලැයිස්තුවක් සැපයිය හැකිය.
print(a[[2,5,7]]) # Or directly

[ 0  7 19]
[ 0  7 19]


We can also assign to multiple elements through fancy indexing:

In [7]:
a[idx] = -1
print(a)

[12 15 -1  3  3 -1  9 -1 18  4  6 12  1  6  7 14 17  5 13  8]


Fancy indexing works also for higher dimensional arrays:

In [13]:
b=np.arange(16).reshape(4,4)
print(b)
row=np.array([0,2])
col=np.array([1,3])
print(b[row,col])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 1 11]


## Fancy Indexing With Two Arrays — Simply

This is another form of indexing (recall: indexing = selecting elements with `[ ]`). Here, two arrays of positions are used together to **pick out individual elements by their (row, column) coordinates**. Let's trace it.

---

### The Setup

```python
b = np.arange(16).reshape(4, 4)
```

`np.arange(16)` makes `[0, 1, 2, ..., 15]`, and `.reshape(4, 4)` folds it into a 4×4 grid:

```
b:
        col0 col1 col2 col3
row0  [  0    1    2    3 ]
row1  [  4    5    6    7 ]
row2  [  8    9   10   11 ]
row3  [ 12   13   14   15 ]
```

---

### The Two Index Arrays

```python
row = np.array([0, 2])
col = np.array([1, 3])
```

```python
b[row, col]
```

**The key idea:** these two arrays are read **in parallel, position by position** — pairing up `row[0]` with `col[0]`, then `row[1]` with `col[1]`, and so on. Each pair is a **(row, column) coordinate** pointing to one element.

---

### Pairing Them Up — Element by Element

```
row:  [0, 2]
col:  [1, 3]
       │  │
       │  └── pair 2: (row 2, col 3)
       └───── pair 1: (row 0, col 1)
```

So NumPy reads:
- **1st pair:** `(row 0, col 1)` → element at row 0, column 1
- **2nd pair:** `(row 2, col 3)` → element at row 2, column 3

---

### Looking Up Each Coordinate in `b`

```
b:
        col0 col1 col2 col3
row0  [  0   [1]   2    3 ]     ← (0, 1) → 1
row1  [  4    5    6    7 ]
row2  [  8    9   10  [11]]     ← (2, 3) → 11
row3  [ 12   13   14   15 ]
```

- `(0, 1)` → **1**
- `(2, 3)` → **11**

```python
print(b[row, col])
# → [1, 11]
```

---

Note that the result array was one dimensional! The shape of the result array is defined by the shape of the index arrays, not by the shape of the original array. The next example will demonstrate this.

In [16]:
raw2=np.array([
    [0,0],
    [2,2]
])
col2=np.array([
    [1,3],
    [1,3]
])
print(raw2)
print(col2)
print(b[raw2, col2])

[[0 0]
 [2 2]]
[[1 3]
 [1 3]]
[[ 1  3]
 [ 9 11]]


## 2D Fancy Indexing — The Result Takes the Shape of the Index Arrays

This is the same "pair them up position-by-position" idea as before, but now the index arrays are **2D** — and a key new rule appears: **the result has the same shape as the index arrays.** Let's trace it.

---

### The Setup (same `b` as before)

```
b:
        col0 col1 col2 col3
row0  [  0    1    2    3 ]
row1  [  4    5    6    7 ]
row2  [  8    9   10   11 ]
row3  [ 12   13   14   15 ]
```

### The 2D Index Arrays

```python
row2 = np.array([[0, 0],
                 [2, 2]])      # shape (2, 2)

col2 = np.array([[1, 3],
                 [1, 3]])      # shape (2, 2)
```

Both are 2×2 grids of positions.

---

### The Rule — Pair Element-by-Element, Keep the Shape

Just like before, `row2` and `col2` are read **in parallel, position by position** — but now each position is a spot in a 2×2 grid. Each `(row2[i,j], col2[i,j])` pair is one coordinate:

```
Position [0,0]:  row2=0, col2=1  →  (0, 1)
Position [0,1]:  row2=0, col2=3  →  (0, 3)
Position [1,0]:  row2=2, col2=1  →  (2, 1)
Position [1,1]:  row2=2, col2=3  →  (2, 3)
```

**Line up the two arrays and zip each cell:**

```
row2:  [[0, 0],       col2:  [[1, 3],
        [2, 2]]               [1, 3]]

Pairing each cell:
   [[ (0,1)  (0,3) ],
    [ (2,1)  (2,3) ]]
```

---

### Look Up Each Coordinate in `b`

```
(0, 1) → 1        (0, 3) → 3
(2, 1) → 9        (2, 3) → 11
```

```
b:
        col0 col1 col2 col3
row0  [  0   [1]   2   [3]]     ← (0,1)→1,  (0,3)→3
row1  [  4    5    6    7 ]
row2  [  8   [9]  10  [11]]     ← (2,1)→9,  (2,3)→11
row3  [ 12   13   14   15 ]
```

---

### The Result — Same 2×2 Shape as the Index Arrays

```python
print(b[row2, col2])
# → [[ 1,  3],
#    [ 9, 11]]
```

Notice: the index arrays were **2×2**, so the **result is also 2×2**. The output "inherits" the shape of the index arrays — each coordinate pair's looked-up value sits in the same position the pair occupied.

```
coordinates:        results:
[[ (0,1) (0,3) ]  →  [[  1   3 ]
 [ (2,1) (2,3) ]]     [  9  11 ]]
```

---

### The Key New Idea — Output Shape = Index Array Shape

This is the important takeaway that extends the previous example:

```
1D index arrays (length 2)  →  1D result (2 elements):   b[[0,2],[1,3]] → [1, 11]
2D index arrays (shape 2×2) →  2D result (shape 2×2):    b[row2,col2]   → [[1,3],[9,11]]
```

**Whatever shape the index arrays have, the result has that same shape** — because there's one output value per coordinate pair, arranged in the same layout as the pairs.

---

### Still NOT a Sub-block — Same Caution as Before

Just like the 1D case, this is **not** selecting a rectangular region. It's still one-value-per-coordinate-pair. It just *happens* to look grid-like here because the coordinates were arranged in a grid. Each output value comes from exactly one `(row, col)` pair — no "all combinations" happening.

---

### Visualizing the Whole Thing

```
row2[i,j] ─┐
           ├─→ (row, col) coordinate ─→ look up in b ─→ result[i,j]
col2[i,j] ─┘

[0,0]: (0,1) → 1        [0,1]: (0,3) → 3
[1,0]: (2,1) → 9        [1,1]: (2,3) → 11

           ↓ assembled in the same 2×2 layout
        [[ 1,  3],
         [ 9, 11]]
```

---

### The One-Sentence Summary

> `b[row2, col2]` pairs the two index arrays **element-by-element** — each `(row2[i,j], col2[i,j])` is one (row, column) coordinate — looks up each in `b`, and places the result in the **same position**, so the output has the **same shape as the index arrays** (2×2 here → `[[1,3],[9,11]]`). It's the same "lockstep pairing" as the 1D case, just extended: the result always inherits the index arrays' shape, one value per coordinate pair — still not a rectangular sub-block. 🎯

Both index arrays, row and col, had shape (2,2), so also the result was of shape (2,2). However, this form has some repetition in the indices. But we can rely that the broadcasting rules will enable us to avoid the repetition:

In [19]:
row2=row.reshape(2,1) # has shape (2, 1)
col2=col.reshape(1,2) # has shape (1, 2)
print(row2)
print(col2)

[[0]
 [2]]
[[1 3]]


In [20]:
print(b[row2, col2]) # the index arrays will be broadcasted here to shape (2,2)

[[ 1  3]
 [ 9 11]]


One can also combine normal indexing, slicing and fancy indexing:

In [22]:
print(b)
print(b[:, [0,2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]]
