### Creation of arrays

We start by importing the NumPy library, and we use the standard abbreviation ```np``` for it.

In [2]:
import numpy as np

There are several ways of creating NumPy arrays.

1. One way is to give a (nested) list as a parameter to the ```array``` constructor:

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
print(np.array([1,2,3]).ndim)

1


## No — This Is a Plain (Non-Nested) List

```python
np.array([1, 2, 3])
```

Look at `[1, 2, 3]` carefully — it's just **one level** of brackets, containing **plain numbers** directly:

```
[1, 2, 3]
 │  │  │
 1  2  3      ← each element is just a NUMBER, not another list
```

No list appears **inside** another list here — so this is **not** nested. It's a single, flat list.

---

### Comparing Both Cases Side by Side

```python
np.array([1, 2, 3])              # flat list → 1D array
np.array([[1, 2, 3], [4, 5, 6]])   # NESTED list → 2D array
```

| Code | Structure | Levels of brackets | Result |
|---|---|---|---|
| `[1, 2, 3]` | flat | one `[ ]` | 1D array — a single row |
| `[[1,2,3], [4,5,6]]` | nested | `[ [ ] , [ ] ]` — a list containing lists | 2D array — rows and columns |

---

### Verifying With NumPy

```python
import numpy as np

a = np.array([1, 2, 3])
print(a.ndim)     # → 1     (1-dimensional — confirms: NOT nested)

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.ndim)      # → 2     (2-dimensional — confirms: nested list → 2D array)
```

`.ndim` (number of dimensions) directly reflects how many levels of nesting the original list had.

---

### The Simple Test

> **Ask: does any element of the list contain ANOTHER list?**
>
> `[1, 2, 3]` → elements are `1`, `2`, `3` — plain numbers → **NOT nested** → 1D array
> `[[1,2,3], [4,5,6]]` → elements are `[1,2,3]` and `[4,5,6]` — themselves lists → **nested** → 2D array

---

### The One-Sentence Summary

> No — `[1, 2, 3]` is a **flat**, non-nested list; its elements are plain numbers, not other lists. Nesting only happens when a list's elements are **themselves lists**, like `[[1,2,3], [4,5,6]]` — which is exactly why the first example is labeled a "one dimensional array" and would need actual nesting to become 2D. 🎯

Note that leaving out the brackets from the above expression, i.e. calling ```np.array(1,2,3)``` will result in an error.

In [23]:
np.array(1,2,3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

Two dimensional array can be given by listing the rows of the array:

In [5]:
np.array([
    [1,2,3],
    [4,5,6]
])

array([[1, 2, 3],
       [4, 5, 6]])

Similarly, three dimensional array can be described as a list of lists of lists:

In [9]:
t_d = np.array([
 [[1,2],[3,4]],
 [[5,6],[7,8]]
])

In [11]:
t_d.ndim

3

There are some helper functions to create common types of arrays:

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

To specify that elements are ints instead of floats, use the parameter ```dtype```:

In [13]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

Similarly ones initializes all elements to one, full initializes all elements to a specified value, and empty leaves the elements uninitialized:

In [15]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [16]:
np.full((2,3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

In [18]:
np.empty((2,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

The eye function creates the identity matrix, that is, a matrix with elements on the diagonal are set to one, and non-diagonal elements are set to zero:

In [19]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

The ```arange``` function works like the range function, but produces an array instead of a list.

In [21]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

For non-integer ranges it is better to use ```linspace```:

In [22]:
np.linspace(0,np.pi,5)

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

With linspace one does not have to compute the length of the step, but instead one specifies the wanted number of elements. By default, the endpoint is included in the result, unlike with arange.