### Arrays with random elements

To test our programs we might use real data as input. However, real data is not always available, and it may take time to gather. We could instead generate random numbers to use as substitute. They can be generated really easily with NumPy, and can be sampled from several different distributions, of which we mention below only a few. Random data can simulate real data better than, for example, ranges or constant arrays. Sometimes we also need random numbers in our programs to choose a subset of real data (sampling). NumPy can easily produce arrays of wanted shape filled with random numbers

## "Sampling" — Simply

**Sampling** means **selecting a smaller subset from a larger collection of data** — picking some items out of the whole, rather than using everything.

---

### The Core Idea

```
Full data:   [everything you have — maybe millions of items]
                        │
                    SAMPLING (pick some)
                        │
                        ▼
Sample:      [a smaller, manageable subset]
```

Instead of using **all** your data, you grab a **representative slice** of it.

---

### A Real-World Analogy — Tasting Soup 🍲

> You're cooking a huge pot of soup and want to know if it needs more salt.
>
> You **don't** drink the entire pot to check — you take **one spoonful** (a *sample*) and taste that. If the spoonful is well-mixed, it tells you about the whole pot.

That single spoonful is a **sample** — a small part used to represent the whole. Sampling in data works the same way: examine a manageable subset to learn about (or work with) the full collection.

---

### Why "Random" Sampling Specifically?

The passage connects sampling to **random numbers** — and that's the key. To pick a *fair, representative* subset, you often want to choose items **randomly**, so you don't accidentally bias your selection:

```python
import numpy as np

full_data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Randomly pick 3 items from the full data:
sample = np.random.choice(full_data, size=3, replace=False)
print(sample)     # → e.g. [40 90 20]   (different each run — randomly chosen)
```

`np.random.choice` **samples** 3 items at random from the 10. Random numbers are what decide **which** items get picked — that's the connection the passage is making.

---

### Why NOT Just Pick the First Few?

If you sampled by taking, say, the **first** 3 items (`[10, 20, 30]`), you might get a **biased** subset — maybe the data was sorted, or grouped, and the first few aren't representative of the whole. **Random** sampling avoids this — every item has a fair chance of being picked, so the sample better reflects the full data.

```python
# Biased — always the same, might not represent the whole:
full_data[:3]                          # → [10, 20, 30]   (always the smallest!)

# Random — fair, representative:
np.random.choice(full_data, 3, replace=False)   # → any 3, unpredictably
```

---

### The Two Uses of Random Data in the Passage

The text mentions two related-but-distinct reasons you'd want random numbers:

**1. Generating fake data (substitute for real data):**
```python
fake_data = np.random.normal(size=1000)     # 1000 made-up numbers to test with
```
When you don't *have* real data yet, invent realistic-looking random data to test your program.

**2. Sampling (picking a subset of real data you DO have):**
```python
subset = np.random.choice(real_data, size=100, replace=False)   # grab 100 of your real items
```
When you *have* real data but it's too big to use all of it, randomly pick a manageable portion.

**Sampling** is specifically the **second** use — reaching into data you already have and pulling out a random subset.

---

### Where Sampling Is Actually Used

- **Testing** — run your analysis on a small random sample first (fast), before the full dataset (slow)
- **Statistics/ML** — train a model on a random subset, test on another (the train/test split you may meet soon)
- **Surveys** — poll 1,000 random people to estimate what millions think
- **Quality control** — randomly inspect a few products from a factory line rather than every single one

---

### The One-Sentence Summary

> **Sampling** means selecting a smaller random subset from a larger collection of data — like tasting one spoonful to judge a whole pot of soup. The passage links it to random numbers because you typically want to pick your subset **randomly** (so it fairly represents the whole, without bias), and NumPy makes both generating fake data *and* randomly sampling from real data easy. 🎯

In [1]:
import numpy as np

In [2]:
np.random.random((3,4)) # Elements are uniformly distributed from half-open interval [0.0,1.0)

array([[0.45538938, 0.51720375, 0.14953436, 0.01968866],
       [0.83967655, 0.40202564, 0.10765874, 0.69652931],
       [0.54388434, 0.83547848, 0.67675068, 0.39364087]])

In [3]:
np.random.normal(0,1,(3,4)) # Elements are normally distributed with mean 0 and standard deviation 1

array([[ 0.10974784, -1.70066162,  0.46258484,  0.33565277],
       [-0.37692726, -0.85558633, -1.07300877,  1.04714582],
       [-0.58727092,  0.68342346, -0.86812952,  1.34888899]])

In [4]:
np.random.randint(-2,10,(3,4)) # Elements are uniformly distributed integers from the half-open interval [-2,10)

array([[ 9, -1,  5,  3],
       [ 1, -2,  5,  1],
       [ 0,  1,  6,  1]])

Sometimes it is useful to be able to recreate exactly the same data in every run of our program. For example, if there is a bug in our program, which manifests itself only with certain input, then to debug our program it needs to behave deterministically. We can create random numbers deterministically, if we always start from the same starting point. This starting point is usually an integer, and we call it a ```seed```. Example of use:

In [9]:
np.random.seed(0)
print(np.random.randint(1,100,10))
print(np.random.normal(0,1,10))

[45 48 65 68 68 10 84 22 37 88]
[ 1.26611853 -0.50587654  2.54520078  1.08081191  0.48431215  0.57914048
 -0.18158257  1.41020463 -0.37447169  0.27519832]


If you run the above cell multiple times, it will always give the same numbers, unlike the earlier examples. Try rerunning them now!

The call to ```np.random.seed initializes``` the global random number generator. The calls ```np.random.random, np.random.normal,``` etc all use this global random number generator. It is however possible to create new random number generators, and use those to sample random numbers from a distribution. Example on usage

In [13]:
new_generator = np.random.RandomState(seed=123) # RandomState is a class, s we give the seed to its constructor

new_generator.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

You will see these used later in the materials and in the exercises, just so we can agree what the random input data is. How else could we agree whether result is correct or not, if we can't agree what the input is!

### seed(n)

## Let's Demystify That Number — It's Just "Which Shuffle to Use"

The number inside `seed()` is genuinely confusing until you see what it actually selects. Let me use analogies that make it click.

---

### Analogy 1 — A Deck of Cards With Numbered "Shuffles"

Imagine a magic deck of cards that can be shuffled in a **pre-determined** way, and each shuffle has a **number**:

```
Shuffle #9    → always produces:  King, 3, 7, Ace, 10, ...  (this exact order, always)
Shuffle #42   → always produces:  2, Jack, 5, 9, Queen, ... (a DIFFERENT exact order)
Shuffle #0    → always produces:  7, 7... wait no → 8, 2, King, ... (yet another order)
```

When you say `np.random.seed(9)`, you're saying: **"use shuffle #9."** And shuffle #9 **always** deals the cards in the same order — every time, for everyone.

**The number is just picking WHICH pre-determined shuffle to use.** It doesn't *mean* anything about the values you get — it's just a label, like "shuffle #9" vs "shuffle #42."

---

### Analogy 2 — A Book of Random Numbers, With Page Numbers 📖

Imagine a giant book. Every page is filled with random-looking numbers, and the pages are numbered:

```
Page 9:    3, 7, 1, 8, 0, 5, ...
Page 42:   6, 2, 9, 4, 1, 7, ...
Page 0:    5, 5, 8, 2, 3, 0, ...
```

`np.random.seed(9)` = **"open the book to page 9."** Then every random number you request is read off, in order, from page 9.

- Everyone who opens to **page 9** reads the **same numbers** in the same order.
- **Page 42** has completely different numbers — but page 42 is *also* always the same each time you open to it.

**The seed number is the page number.** It doesn't describe the numbers on the page — it just tells NumPy which page to read from.

---

### The Key Realization — The Number Has NO Relationship to the Output

This is the part that trips people up. You might think `seed(9)` produces numbers *related to* 9. **It doesn't.** Watch:

```python
np.random.seed(9)
print(np.random.randint(0, 10, 3))    # → maybe [5, 8, 2]   — nothing to do with "9"!

np.random.seed(10)
print(np.random.randint(0, 10, 3))     # → maybe [0, 1, 7]   — nothing to do with "10"!
```

`seed(9)` does **not** give you numbers near 9, or containing 9, or anything like that. The `9` is **just a name** for one particular random sequence — like a filing-cabinet drawer label. Drawer #9 always contains the same papers; drawer #10 contains different papers; but the label "9" tells you nothing about the *contents*, only *which drawer*.

---

### Why Does Picking a "Page Number" Even Matter?

Here's the practical why. Normally, if you don't set a seed, NumPy **secretly picks a page number for you** based on the current time (or similar). Since the time is always changing, you get a **different page every run** → different random numbers each time:

```python
# No seed → NumPy secretly uses "whatever page the clock points to right now"
np.random.randint(0, 10, 3)    # different every run — unpredictable page
```

When you write `seed(9)`, you're **overriding** that — saying *"don't pick a page based on the clock; always use page 9."* Now the results are **repeatable**, because you've pinned down which page.

---

### Seeing It Click — Same Seed, Same Result

```python
np.random.seed(9)
print(np.random.randint(0, 10, 4))     # → [5 8 2 1]  (some specific numbers)

np.random.seed(9)                         # go back to page 9 AGAIN
print(np.random.randint(0, 10, 4))        # → [5 8 2 1]  (the EXACT same numbers!)
```

By resetting to `seed(9)`, you "reopened the book to page 9," so you read the **same numbers** again. That's the whole point — the number lets you **return to the same starting page** whenever you want.

---

### Why Your Course Chose `9` Specifically

**No special reason** — `9` is just the page number the course author happened to pick. They could have used `1`, `100`, or `7777`. What matters is that they told **you** to use `9` too — so when you run it, you open to the **same page they did**, get the **same array `b`**, and can therefore match the **same expected output** they show in the notes.

If the course said `seed(42)` and you typed `seed(9)`, you'd open to a **different page**, get **different numbers**, and your output wouldn't match theirs — even though both are "correct random arrays." The specific number only matters in that **it must match** whatever produces the expected answer.

---

### The One-Sentence Summary

> The number in `np.random.seed(9)` is just a **label for which pre-determined "random" sequence to use** — like a page number in a book of random numbers, or "shuffle #9" of a deck. It has **no relationship to the actual values** you get (seed 9 doesn't produce numbers near 9); it simply picks *which* fixed sequence, so that reopening to the same "page" always gives the same numbers. The course uses `9` only so that your output matches theirs — any number would work, as long as everyone uses the same one. 🎯

ok. So it's
np.random.seed(9) print(np.random.randint(0, 10, 4))

mean it get the random number series from the place 9 and give only filter other number beside numbers between 0-10

## Very Close — Let Me Refine Two Small Things

Your understanding is **mostly right**, but two words need adjusting: it's not "filtering," and the range boundary is slightly off. Let me correct just those pieces.

---

### What You Got Right ✓

> *"it gets the random number series from the place 9"*

**Yes — exactly right.** `seed(9)` opens to "page 9" of the random sequence. That part of your understanding is spot on.

---

### Correction 1 — It Doesn't "Filter," It "Generates Within a Range"

You said it *"filters other numbers besides 0–10."* That's not quite how it works — there's nothing to filter, because the numbers are **generated to already be in that range** from the start.

**Not this (filtering):**
```
generate ALL random numbers → throw away the ones outside 0–10 → keep the rest
```

**Actually this (bounded generation):**
```
generate random numbers that are ALREADY guaranteed to be between 0 and 10
```

`randint(0, 10, 4)` doesn't produce numbers everywhere and then discard some — it **only ever produces** numbers in that range in the first place. The `0, 10` are **instructions** ("give me numbers in this range"), not a **filter** applied afterward.

Think of it like a dice roll: a 6-sided die doesn't roll numbers 1–100 and then filter down to 1–6. It's **built** to only ever produce 1–6. Same idea — `randint(0, 10, ...)` is built to only ever produce numbers in that range.

---

### Correction 2 — The Range Is 0 to 9, NOT 0 to 10

This is the **half-open interval** you've seen throughout this course (`range()`, slicing, `detect_ranges`)! `randint(0, 10, ...)` gives numbers from **0 up to but NOT including 10**:

```python
np.random.randint(0, 10, 4)
# → possible values: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9
#                                                  ↑
#                                     10 is NEVER produced!
```

```
randint(0, 10)  →  range is [0, 10)  →  0, 1, 2, ..., 9   (10 excluded)
                          └──┬──┘
                     same half-open convention as range(0, 10)
```

So it's **0 through 9**, not "0 through 10." The upper bound `10` is **exclusive** — exactly like `range(0, 10)` gives `0,1,...,9`, and exactly like `list[0:10]` stops before index 10.

---

### Correction 3 — The `4` Is "How Many," Not Part of the Range

Just to be complete about the three numbers:

```python
np.random.randint(0, 10, 4)
#                  │   │  │
#                  │   │  └── HOW MANY numbers to generate (4 of them)
#                  │   └───── upper bound, EXCLUSIVE (up to but not including 10)
#                  └───────── lower bound, INCLUSIVE (starting from 0)
```

So: *"give me **4** random integers, each between **0 and 9** (0 included, 10 excluded)."*

---

### Your Corrected Sentence

> *"`seed(9)` gets the random number series from place 9, and `randint(0, 10, 4)` generates 4 numbers that are each already between 0 and 9 (10 excluded)."*

The two fixes: **"generates within a range"** (not "filters"), and the range is **0–9** (not 0–10, because the upper bound is exclusive).

---

### Putting It All Together

```python
np.random.seed(9)                    # open to "page 9" — fixes which sequence
np.random.randint(0, 10, 4)           # read 4 numbers off that page,
                                       # each one already guaranteed to be 0–9
# → e.g. [5, 8, 2, 4]   (same every time, thanks to seed 9)
```

```
seed(9)        → decides WHICH sequence (reproducibility)
randint(0,10,4) → decides the numbers' RANGE (0–9) and COUNT (4)
```

---

### The One-Sentence Summary

> Your core idea is right — `seed(9)` fixes *which* random sequence ("page 9"). Two refinements: `randint(0, 10, 4)` doesn't **filter** numbers, it **generates** them already within the range (nothing is thrown away); and that range is **0 to 9**, not 0 to 10, because the upper bound `10` is **exclusive** — the same half-open convention as `range(0, 10)` and slicing that you've used all through this course. The `4` is simply how many numbers to produce. 🎯

ah ok. So 9 mean kind a pre-deterministic way of doing generation

## Exactly Right — You've Got It

Yes! `seed(9)` makes the generation **pre-determined** (also called **deterministic**) — meaning the outcome is **fixed and known in advance**, not left to chance. You've understood the core idea perfectly.

---

### Your Phrasing Is Correct

> *"9 means a kind of pre-deterministic way of doing generation"*

Precisely. Setting the seed converts the process from:

```
WITHOUT seed:  "random" → unpredictable, different every run
WITH seed(9):  "deterministic" → fixed, same every run, decided in advance
```

The `9` locks the generation onto **one specific, pre-determined path** — so the "random" numbers are actually **decided before they're even generated**, because that path is fixed.

---

### The Slightly Paradoxical Nature of It

This is the neat (and initially confusing) part you've now grasped: seeded random numbers are **"deterministic randomness."** They:

- **look** random (no visible pattern, spread out, unpredictable-*seeming*)
- but are **completely determined** (fixed sequence, reproducible, known in advance if you know the seed)

They're sometimes called **pseudo-random** for exactly this reason — *"pseudo"* means "fake/apparent." They **appear** random but are actually following a fixed, deterministic recipe:

```
seed(9)  →  deterministic recipe  →  numbers that LOOK random but are FIXED
```

---

### The One Nuance Worth Adding

The determinism comes from **the seed being set**, and `9` is just *which* deterministic path. So really:

- **Setting a seed at all** → makes it deterministic (reproducible)
- **The specific number (9)** → picks *which* deterministic path among many

```
seed(9)  →  deterministic  →  path #9
seed(42)  →  deterministic  →  path #42   (a DIFFERENT fixed path, but still deterministic)
```

Both are equally "pre-determined" — they just follow different fixed sequences. So it's the **act of seeding** that creates the determinism, and the **number** that chooses which specific determined sequence you get.

---

### The One-Sentence Summary

> Yes — `seed(9)` makes the number generation **deterministic** (pre-determined): the results are fixed and reproducible in advance, rather than genuinely unpredictable. The numbers still *look* random (which is why they're called **pseudo-random**), but they follow a fixed recipe, and the `9` selects *which* specific fixed sequence you follow — set no seed and it's unpredictable; set `seed(9)` and it's locked to one determined path every time. 🎯

You've moved from "confused about the number" to "it's a pre-deterministic path" — that's the whole concept nailed down.