### Arrays with random elements

To test our programs we might use real data as input. However, real data is not always available, and it may take time to gather. We could instead generate random numbers to use as substitute. They can be generated really easily with NumPy, and can be sampled from several different distributions, of which we mention below only a few. Random data can simulate real data better than, for example, ranges or constant arrays. Sometimes we also need random numbers in our programs to choose a subset of real data (sampling). NumPy can easily produce arrays of wanted shape filled with random numbers

## "Sampling" — Simply

**Sampling** means **selecting a smaller subset from a larger collection of data** — picking some items out of the whole, rather than using everything.

---

### The Core Idea

```
Full data:   [everything you have — maybe millions of items]
                        │
                    SAMPLING (pick some)
                        │
                        ▼
Sample:      [a smaller, manageable subset]
```

Instead of using **all** your data, you grab a **representative slice** of it.

---

### A Real-World Analogy — Tasting Soup 🍲

> You're cooking a huge pot of soup and want to know if it needs more salt.
>
> You **don't** drink the entire pot to check — you take **one spoonful** (a *sample*) and taste that. If the spoonful is well-mixed, it tells you about the whole pot.

That single spoonful is a **sample** — a small part used to represent the whole. Sampling in data works the same way: examine a manageable subset to learn about (or work with) the full collection.

---

### Why "Random" Sampling Specifically?

The passage connects sampling to **random numbers** — and that's the key. To pick a *fair, representative* subset, you often want to choose items **randomly**, so you don't accidentally bias your selection:

```python
import numpy as np

full_data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Randomly pick 3 items from the full data:
sample = np.random.choice(full_data, size=3, replace=False)
print(sample)     # → e.g. [40 90 20]   (different each run — randomly chosen)
```

`np.random.choice` **samples** 3 items at random from the 10. Random numbers are what decide **which** items get picked — that's the connection the passage is making.

---

### Why NOT Just Pick the First Few?

If you sampled by taking, say, the **first** 3 items (`[10, 20, 30]`), you might get a **biased** subset — maybe the data was sorted, or grouped, and the first few aren't representative of the whole. **Random** sampling avoids this — every item has a fair chance of being picked, so the sample better reflects the full data.

```python
# Biased — always the same, might not represent the whole:
full_data[:3]                          # → [10, 20, 30]   (always the smallest!)

# Random — fair, representative:
np.random.choice(full_data, 3, replace=False)   # → any 3, unpredictably
```

---

### The Two Uses of Random Data in the Passage

The text mentions two related-but-distinct reasons you'd want random numbers:

**1. Generating fake data (substitute for real data):**
```python
fake_data = np.random.normal(size=1000)     # 1000 made-up numbers to test with
```
When you don't *have* real data yet, invent realistic-looking random data to test your program.

**2. Sampling (picking a subset of real data you DO have):**
```python
subset = np.random.choice(real_data, size=100, replace=False)   # grab 100 of your real items
```
When you *have* real data but it's too big to use all of it, randomly pick a manageable portion.

**Sampling** is specifically the **second** use — reaching into data you already have and pulling out a random subset.

---

### Where Sampling Is Actually Used

- **Testing** — run your analysis on a small random sample first (fast), before the full dataset (slow)
- **Statistics/ML** — train a model on a random subset, test on another (the train/test split you may meet soon)
- **Surveys** — poll 1,000 random people to estimate what millions think
- **Quality control** — randomly inspect a few products from a factory line rather than every single one

---

### The One-Sentence Summary

> **Sampling** means selecting a smaller random subset from a larger collection of data — like tasting one spoonful to judge a whole pot of soup. The passage links it to random numbers because you typically want to pick your subset **randomly** (so it fairly represents the whole, without bias), and NumPy makes both generating fake data *and* randomly sampling from real data easy. 🎯

In [1]:
import numpy as np

In [2]:
np.random.random((3,4)) # Elements are uniformly distributed from half-open interval [0.0,1.0)

array([[0.45538938, 0.51720375, 0.14953436, 0.01968866],
       [0.83967655, 0.40202564, 0.10765874, 0.69652931],
       [0.54388434, 0.83547848, 0.67675068, 0.39364087]])

In [3]:
np.random.normal(0,1,(3,4)) # Elements are normally distributed with mean 0 and standard deviation 1

array([[ 0.10974784, -1.70066162,  0.46258484,  0.33565277],
       [-0.37692726, -0.85558633, -1.07300877,  1.04714582],
       [-0.58727092,  0.68342346, -0.86812952,  1.34888899]])

In [4]:
np.random.randint(-2,10,(3,4)) # Elements are uniformly distributed integers from the half-open interval [-2,10)

array([[ 9, -1,  5,  3],
       [ 1, -2,  5,  1],
       [ 0,  1,  6,  1]])

Sometimes it is useful to be able to recreate exactly the same data in every run of our program. For example, if there is a bug in our program, which manifests itself only with certain input, then to debug our program it needs to behave deterministically. We can create random numbers deterministically, if we always start from the same starting point. This starting point is usually an integer, and we call it a ```seed```. Example of use:

In [9]:
np.random.seed(0)
print(np.random.randint(1,100,10))
print(np.random.normal(0,1,10))

[45 48 65 68 68 10 84 22 37 88]
[ 1.26611853 -0.50587654  2.54520078  1.08081191  0.48431215  0.57914048
 -0.18158257  1.41020463 -0.37447169  0.27519832]


If you run the above cell multiple times, it will always give the same numbers, unlike the earlier examples. Try rerunning them now!

The call to ```np.random.seed initializes``` the global random number generator. The calls ```np.random.random, np.random.normal,``` etc all use this global random number generator. It is however possible to create new random number generators, and use those to sample random numbers from a distribution. Example on usage

In [13]:
new_generator = np.random.RandomState(seed=123) # RandomState is a class, s we give the seed to its constructor

new_generator.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

You will see these used later in the materials and in the exercises, just so we can agree what the random input data is. How else could we agree whether result is correct or not, if we can't agree what the input is!