### Indexing

One dimensional array behaves like the list in Python:

In [2]:
import numpy as np

In [3]:
a=np.array([1,4,2,7,9,5])
print(a[1])
print(a[-2])

4
9


For multi-dimensional array the index is a comma separated tuple instead of a single integer:

In [4]:
b=np.array([
    [1,2,3],
    [4,5,6]
])

In [5]:
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
print(b[1,2]) # raw index 1, column index 2

6


In [11]:
print(b[0,-1]) # raw index 0, column index -1

3


In [9]:
# As with lists, modification through indexing is possible
b[0,0] = 10
print(b)

[[10  2  3]
 [ 4  5  6]]


Note that if you give only a single index to a multi-dimensional array, it indexes the first dimension of the array, that is the rows. For example:

In [10]:
print(b[0])
print(b[1])

[10  2  3]
[4 5 6]
