In [3]:
import numpy as np

In [4]:
a=np.array([1,4,2,7,9,5])

Slicing works similarly to lists, but now we can have slices in different dimensions:

In [5]:
print(a)

[1 4 2 7 9 5]


In [6]:
print(a[1:3])

[4 2]


In [7]:
print(a[::-1]) # Reverse the array

[5 9 7 2 4 1]


In [8]:
b=np.array([
    [10,2,3],
    [4,5,6]
])

In [9]:
print(b)

[[10  2  3]
 [ 4  5  6]]


In [10]:
print(b[:,0])

[10  4]


In [12]:
print(b[0,:])

[10  2  3]


In [13]:
print(b[:,1:])

[[2 3]
 [5 6]]


## Ah — NOW I Understand Your Question! The "To the End" Comes From the EMPTY Space After the Colon

You've got everything right — I misread what you were asking. Your actual question is: **"where does the 'to the end' part come from?"** The answer: it's the **blank/nothing after the colon**. Let me show you exactly.

---

### The `1:` Has an Invisible "Nothing" After the Colon

```
1  :  ⟨nothing⟩
│  │      │
│  │      └── the LAST/end is BLANK — and blank means "to the very end"
│  └───────── the colon
└──────────── the first/start = 1
```

**That empty space after the colon IS the "to the end" part.** When you leave the `last` position blank, Python interprets that blank as *"keep going all the way to the end."*

---

### Making the Invisible Part Visible

Your array has 3 columns (indices 0, 1, 2). These are all identical:

```python
b[:, 1:]      # blank after colon
b[:, 1:3]      # explicitly writing the end as 3 (one past the last column)
b[:, 1:100]     # even a too-big number — clamped to the actual end
```

All three give:
```python
# → [[2, 3],
#    [5, 6]]
```

**`1:` and `1:3` are the same** — because leaving the end blank **means** "go to the end," and the end happens to be column index 2 (so `last=3`, since slicing is exclusive of the last).

---

### The Rule — A Blank Slot Has a Default Meaning

Each of the three slice positions has a **default** it falls back to when you leave it empty:

```
first : last : step
  │      │      │
  ↓      ↓      ↓
default: default: default:
  0      END      1
"start" "all the "every
        way to    one"
        the end"
```

So in `1:`:
```
first = 1        (you specified it)
last  = <blank>  → defaults to END  ← THIS is your "to the end"
step  = <blank>  → defaults to 1
```

**The "to the end" isn't written anywhere — it's the *default* that fills the empty `last` slot.**

---

### Proving the Blank = "End" With Contrast

Watch what happens when you **do** fill in the `last`:

```python
b[:, 1:2]     # last = 2 → columns 1 up to (not including) 2 → JUST column 1
# → [[2],
#    [5]]

b[:, 1:]       # last = BLANK → "to the end" → columns 1 AND 2
# → [[2, 3],
#    [5, 6]]
```

- `1:2` — you **filled** the last with `2`, so it stops early (only column 1)
- `1:` — you **left** the last blank, so it defaults to "the end" (columns 1 and 2)

**The only difference is whether that spot after the colon is filled or empty.** Empty = "to the end."

---

### Even the Bare `:` Works This Way

This is why a lone `:` (like the row selector) means "everything":

```
:
│
first = <blank> → defaults to 0 (start)
last  = <blank> → defaults to END
step  = <blank> → defaults to 1

→ "from start to end" = everything
```

Both slots blank → "from the very beginning to the very end" → all of it.

---

### The One-Sentence Answer to Your Actual Question

> The "to the end" part comes from the **empty space after the colon** in `1:` — when you leave the `last` position blank, Python fills it with its **default**, which is "all the way to the end." So `1:` literally means `first=1, last=(defaults to the end), step=(defaults to 1)` — the "to the end" is never written; it's the automatic default that fills the blank `last` slot, exactly the same way a lone `:` means "everything" because *both* its slots are blank. 🎯

We can even assign to a slice:

In [14]:
b[:,1:] = 7

In [15]:
print(b)

[[10  7  7]
 [ 4  7  7]]


A common idiom is to extract rows or columns from an array:

In [16]:
print(b[:,0])
print(b[1,:])

[10  4]
[4 7 7]
