<img src="images/image2.png" width='1000'>

In [2]:
import numpy as np

In [35]:
def get_rows(a):
    return list(a)

In [36]:
def get_columns(a):
 return list(a.T)

In [37]:
a = np.array([
 [5, 0, 3, 3],
 [7, 9, 3, 5],
 [2, 4, 7, 6],
 [8, 8, 1, 6]
])

In [38]:
get_rows(a)

[array([5, 0, 3, 3]),
 array([7, 9, 3, 5]),
 array([2, 4, 7, 6]),
 array([8, 8, 1, 6])]

In [39]:
get_columns(a)

[array([5, 7, 2, 8]),
 array([0, 9, 4, 8]),
 array([3, 3, 7, 1]),
 array([3, 5, 6, 6])]

## `list(a)` on a 2D NumPy Array — What It Actually Does

This converts the array into a **Python list**, but the result might surprise you — it only "unpacks" the **outermost** dimension, leaving the inner rows as NumPy arrays.

---

### What You Get

```python
list(a)
```

```python
[array([5, 0, 3, 3]),
 array([7, 9, 3, 5]),
 array([2, 4, 7, 6]),
 array([8, 8, 1, 6])]
```

**A Python list containing 4 NumPy arrays** — one array per row. The outer structure became a real `list`, but each row inside is **still a NumPy array**, not a Python list.

---

### Why This Happens — `list()` Iterates the Object

Remember from your `list()`/iterable lessons — `list(x)` walks through `x` **one element at a time** (using the iterator protocol) and collects those elements into a list. So the question becomes: *when you iterate a 2D NumPy array, what do you get?*

**Iterating a 2D array yields its rows** — one row per step:

```python
for row in a:
    print(row)
```
```
[5 0 3 3]
[7 9 3 5]
[2 4 7 6]
[8 8 1 6]
```

Each `row` is a 1D NumPy array. So `list(a)` collects exactly these — **4 row-arrays** bundled into a Python list.

---

### The Key Insight — `list()` Only Goes ONE Level Deep

`list()` converts **only the top level**. It doesn't recurse into the inner rows to convert those too:

```python
result = list(a)

type(result)        # → <class 'list'>              ← outer is a Python list ✓
type(result[0])      # → <class 'numpy.ndarray'>     ← inner rows are STILL arrays!
```

So you get a **mixed** structure: a Python list on the outside, NumPy arrays on the inside.

---

### If You Want a FULLY Python List (Lists All the Way Down)

Use NumPy's `.tolist()` method instead — it converts **every** level:

```python
a.tolist()
```
```python
[[5, 0, 3, 3],
 [7, 9, 3, 5],
 [2, 4, 7, 6],
 [8, 8, 1, 6]]
```

```python
result = a.tolist()
type(result)        # → <class 'list'>     outer is a list
type(result[0])      # → <class 'list'>     inner rows are ALSO lists!
type(result[0][0])    # → <class 'int'>       even the numbers are Python ints
```

**`.tolist()` recurses through all dimensions**, giving you a pure nested Python list with no NumPy objects anywhere.

---

### Side-by-Side Comparison

| | `list(a)` | `a.tolist()` |
|---|---|---|
| Outer structure | Python `list` | Python `list` |
| Inner rows | NumPy `array`s | Python `list`s |
| Individual numbers | NumPy int types | Python `int`s |
| Depth converted | **one level** (top only) | **all levels** (fully recursive) |

---

### Why the Difference Matters

If you plan to do anything **NumPy-specific** with the rows (math, slicing), `list(a)` keeps them as arrays — which might be what you want:

```python
rows = list(a)
rows[0] * 2      # → array([10, 0, 6, 6])   still works — it's a NumPy array!
```

But if you need a **pure Python** structure (e.g., to JSON-serialize, or pass to code that expects plain lists), `.tolist()` is the right choice:

```python
import json
json.dumps(a.tolist())     # ✓ works — plain lists/ints are JSON-serializable
json.dumps(list(a))         # ✗ TypeError — NumPy arrays aren't JSON-serializable
```

---

### The One-Sentence Summary

> `list(a)` on a 2D array converts **only the outermost dimension** into a Python list, iterating the array row by row — so you get a Python `list` containing NumPy `array`s (one per row), not a fully Python structure. To convert **every** level (rows and the numbers inside them) into pure Python lists and ints, use NumPy's `.tolist()` method instead, which recurses through all dimensions. 🎯