<img src="images/image1.png" width=600>

In [1]:
import numpy as np

In [3]:
a=np.array([
 [8, 9, 3, 8, 8],
 [0, 5, 3, 9, 9],
 [5, 7, 6, 0, 4],
 [7, 8, 1, 6, 2],
 [2, 1, 3, 5, 8]
])

In [8]:
print(a[:,1] > a[:,-2])

[ True False  True  True False]


In [9]:
x=a[:,1] > a[:,-1]
print(a[x])

[[8 9 3 8 8]
 [5 7 6 0 4]
 [7 8 1 6 2]]
