In [1]:
import numpy as np

In [41]:
a=np.array([
    [1,3,4,2],
    [2,2,1,2]
])

r,c = a.shape
dl = c/2
print(r,c, int(dl))

2 4 2


In [42]:
a1=a[:,: int(c/2)]
a1

array([[1, 3],
       [2, 2]])

In [23]:
a1.sum(axis=1)

array([4, 4])

In [43]:
a2=a[:,int(dl):]
a2

array([[4, 2],
       [1, 2]])

In [44]:
c =a1.sum(axis=1) > a2.sum(axis=1)

In [45]:
a[c]

array([[2, 2, 1, 2]])

In [47]:
def first_half_second_half(a):
    r,c = a.shape
    a1=a[:,:int(c/2)]
    a2=a[:,int(c/2):]
    c =a1.sum(axis=1) > a2.sum(axis=1)
    return a[c]

In [48]:
first_half_second_half(a)

array([[2, 2, 1, 2]])