### Broadcasting

We have seen that NumPy allows array operations that are performed element-wise. But NumPy also allows binary operations that don't require the two arrays to have the same shape. For example, we can add 4 to all elements of an array with the following expression:

In [3]:
import numpy as np

In [10]:
def info(name, a):
    print(f"{name} has dim {a.ndim}, shape {a.shape}, size {a.size}, and dtype {a.dtype}:")
    print(a)

In [4]:
np.arange(3) + np.array([4])

array([4, 5, 6])

In fact, because an array with only one element, say 4, can be thought of as a `scalar 4`, NumPy allows the following expression, which is equivalent to the above:

First — "Scalar" Just Means "A Single Number"

```
scalar   = a single, plain number:   4,  7,  3.14,  -2

array    = a collection of numbers:  [4],  [1,2,3],  [[1,2],[3,4]] ```

In [5]:
np.arange(3) + 4

array([4, 5, 6])

To get an idea of what operations are allowed, i.e. what shapes of the two arrays are compatible, it can be useful to think that before the binary operation is performed, NumPy tries to stretch the arrays to have the same shape. For example, above, NumPy first stretched the array `np.array([4])` (or the scalar 4), to the array `np.array([4,4,4])` and then performed the element-wise addition. In NumPy this stretching is called broadcasting.

The argument arrays can of course have higher dimensions, as the next example shows:

<img src ="images/image1.png" width=600>

What "Argument" Means Generally

An argument is a value you pass into a function or operation for it to work on:

In [ ]:
len([1, 2, 3])       # [1,2,3] is the ARGUMENT to len()
np.sqrt(16)           # 16 is the ARGUMENT to np.sqrt()
a + b                  # a and b are the ARGUMENTS to the +

len([1, 2, 3])       # [1,2,3] is the ARGUMENT to len()
np.sqrt(16)           # 16 is the ARGUMENT to np.sqrt()
a + b                  # a and b are the ARGUMENTS to the + operation

In [8]:
a=np.full((3,3),5)
b=np.arange(3)
print('a:', sep='\n')
print('b:', b)
print('a+b:', a+b, sep='\n')

a:
b: [0 1 2]
a+b:
[[5 6 7]
 [5 6 7]
 [5 6 7]]


In this example the second argument was first broadcasted to the array


In [ ]:
np.array([
    [0,1,2],
    [0,1,2],
    [0,1,2]
])

and then the addition was performed. And it may be that both of the argument arrays need to be broadcasted as in the next example:

In [12]:
a=np.arange(3)
b=np.arange(3).reshape((3,1))
info('a',a)
info('b',b)
info('a+b',a+b)

a has dim 1, shape (3,), size 3, and dtype int64:
[0 1 2]
b has dim 2, shape (3, 1), size 3, and dtype int64:
[[0]
 [1]
 [2]]
a+b has dim 2, shape (3, 3), size 9, and dtype int64:
[[0 1 2]
 [1 2 3]
 [2 3 4]]


To see what the arguments were broadcasted to before the binary operation, the function np.broadcast_arrays can be used:

In [13]:
broadcasted_a, broadcastest_b = np.broadcast_arrays(a,b)
info('broadcasted_a', broadcasted_a)
info('broadcastest_b', broadcastest_b)

broadcasted_a has dim 2, shape (3, 3), size 9, and dtype int64:
[[0 1 2]
 [0 1 2]
 [0 1 2]]
broadcastest_b has dim 2, shape (3, 3), size 9, and dtype int64:
[[0 0 0]
 [1 1 1]
 [2 2 2]]


So, both arrays were broadcasted, but in different ways. Let's next go through the rules how the broadcasting work.

1. All input arrays with ndim smaller than the input array of largest ndim, have 1’s prepended to their shapes.
2. The size in each dimension of the output shape is the maximum of all the input sizes in that dimension.
3. An input can be used in the calculation if its size in a particular dimension either matches the output size in that dimension, or has value exactly 1.
4. If an input has a dimension size of 1 in its shape, the first data entry in that dimension will be used for all calculations along that dimension. In other words, the stepping machinery of the ufunc will simply not step along that dimension (the stride will be 0 for that dimension).

Got it — here's your original explanation document with **only Rule 3's content corrected** (input-vs-output instead of input-vs-input), and everything else left exactly as it was.

---

## The Broadcasting Rules — Explained Simply With Examples

These four rules are NumPy's official recipe for deciding **whether two differently-shaped arrays can be combined, and how**. Let me translate each into plain language with a worked example.

---

### The Running Example

```python
a = np.full((3, 3), 5)     # shape (3, 3)
b = np.arange(3)            # shape (3,)
a + b
```

```
a (3,3):          b (3,):
[[5 5 5]          [0 1 2]
 [5 5 5]
 [5 5 5]]
```

We'll trace all four rules on this.

---

### Rule 1 — "Prepend 1's to make the shapes the same length"

> *All input arrays with fewer dimensions get `1`s added to the FRONT of their shape.*

`a` has shape `(3, 3)` — **2 dimensions**. `b` has shape `(3,)` — only **1 dimension**. To compare them, they need the **same number of dimensions**. So NumPy **prepends a 1** to the shorter one:

```
a: (3, 3)     ← already 2D, unchanged
b: (3,)   →   (1, 3)     ← a 1 is added to the FRONT
```

Now both are 2D: `(3, 3)` and `(1, 3)`. Think of `b` going from a flat `[0,1,2]` to a single-row `[[0,1,2]]`.

**Why "prepend" (front, not back)?** It's the rule — the extra dimension is always added at the **beginning**. This matters (adding to the back would give different results).

---

### Rule 2 — "Output size in each dimension = the biggest input in that dimension"

> *For each dimension, the result's size is the maximum of the inputs' sizes there.*

Line up the shapes dimension by dimension and take the max of each:

```
a:       (3, 3)
b:       (1, 3)
          │  │
          │  └── dim 1: max(3, 3) = 3
          └───── dim 0: max(3, 1) = 3

output:  (3, 3)
```

So the result will be shape `(3, 3)`. The `1` in `b`'s shape "loses" to the `3` in `a`'s — the bigger one wins.

---

### Rule 3 — "Each input is compatible if its size MATCHES THE OUTPUT or is 1"

> *In each dimension, an input works only if its size equals the **output** size, OR its size is exactly 1. (Each input is checked against the output shape — not against the other input.)*

This is the **compatibility check** — it tells you whether broadcasting is even *allowed*. The output shape here is `(3, 3)` (from Rule 2), and each input is checked against **it**:

```
Output = (3, 3)

Check a (3, 3) against output:
  dim 0:  a has 3, output has 3  →  matches output ✓
  dim 1:  a has 3, output has 3  →  matches output ✓

Check b (1, 3) against output:
  dim 0:  b has 1  →  is exactly 1 → OK ✓ (stretches to output's 3)
  dim 1:  b has 3, output has 3  →  matches output ✓
```

Both inputs pass in every dimension → broadcasting is allowed.

**If an input's size in a dimension neither matches the output NOR is 1**, it would fail:
```
(3, 4) + (3, 2)  →  output dim 1 = max(4,2) = 4
                    input (3,2): dim 1 has 2 → not 4, not 1 → ✗ ERROR!
# "operands could not be broadcast together"
```

So the rule is: in each dimension, each input must either **match the output** or have a **1** (which can stretch). Anything else is an error.

---

### Rule 4 — "A dimension of size 1 gets REUSED (stretched) for all positions"

> *If an input has size 1 in a dimension, its single entry is reused across that whole dimension — the operation just doesn't "step" along it.*

This is the actual **stretching**. `b` has size `1` in dimension 0 (it's `(1, 3)` = one row). So that **single row gets reused for all 3 output rows**:

```
b is (1, 3):   [[0, 1, 2]]     ← just ONE row

Stretched to (3, 3) by REUSING that row:
   [[0, 1, 2]      ← row 0: the original row
    [0, 1, 2]       ← row 1: SAME row reused
    [0, 1, 2]]       ← row 2: SAME row reused again
```

NumPy doesn't actually **copy** the data in memory (that's the "stride 0" technical detail — it just keeps reading the same row without moving) — but *conceptually*, the size-1 dimension is stretched to fill the output.

---

### Putting All Four Together — The Full Trace

```python
a + b    # a is (3,3), b is (3,)
```

```
RULE 1 — prepend 1 to b:
   a: (3, 3)
   b: (3,)  →  (1, 3)

RULE 2 — output shape = max per dimension:
   (3, 3) vs (1, 3)  →  output (3, 3)

RULE 3 — check each input against the output (3, 3):
   a (3,3): dim 0: 3 matches output 3 ✓;  dim 1: 3 matches output 3 ✓
   b (1,3): dim 0: 1 is 1 → OK ✓;          dim 1: 3 matches output 3 ✓
   → allowed!

RULE 4 — stretch the size-1 dimension:
   b's single row [0,1,2] reused for all 3 rows

FINAL:
   [[5 5 5]     [[0 1 2]     [[5 6 7]
    [5 5 5]  +   [0 1 2]  =   [5 6 7]
    [5 5 5]]     [0 1 2]]      [5 6 7]]
```

Result: `[[5 6 7], [5 6 7], [5 6 7]]` — each row of `a` got `[0,1,2]` added to it.

---

### A Second Example — Stretching in BOTH Arrays

The "broadcasted in different ways" comment refers to cases where **both** inputs stretch. Column vector + row vector:

```python
col = np.array([[10], [20], [30]])    # shape (3, 1)
row = np.array([1, 2, 3])              # shape (3,) → (1, 3) after Rule 1
col + row
```

```
RULE 1:  col (3,1),  row (1,3)
RULE 2:  output = (max(3,1), max(1,3)) = (3, 3)
RULE 3:  check each input against output (3,3):
           col (3,1): dim 0: 3 matches output 3 ✓;  dim 1: 1 is 1 → OK ✓
           row (1,3): dim 0: 1 is 1 → OK ✓;          dim 1: 3 matches output 3 ✓
RULE 4:  col stretches ACROSS columns, row stretches DOWN rows
```

```
col stretched:        row stretched:         sum:
[[10 10 10]           [[1 2 3]               [[11 12 13]
 [20 20 20]     +      [1 2 3]        =        [21 22 23]
 [30 30 30]]           [1 2 3]]                [31 32 33]]
```

**Here BOTH arrays stretched** — `col` reused its single column across all 3 columns, `row` reused its single row down all 3 rows. That's "broadcasted in different ways."

---

### The Rules in Plain English

| Rule | Plain meaning |
|---|---|
| 1 | Make shapes the same length by adding 1's to the front of the shorter one |
| 2 | Output size in each dimension = the bigger of the two inputs there |
| 3 | Allowed only if, in each dimension, each input **matches the output** or is 1 (else error) |
| 4 | A size-1 dimension gets reused (stretched) to fill the output |

---

### The One-Sentence Summary

> Broadcasting lets NumPy combine different-shaped arrays by: **(1)** padding the shorter shape with 1's at the front, **(2)** making the output as big as the largest input in each dimension, **(3)** allowing it only if each dimension of each input either **matches the output** or has a 1 (otherwise error), and **(4)** stretching any size-1 dimension by reusing its single entry across the whole dimension. In `a(3,3) + b(3,)`, `b` becomes `(1,3)`, its single row `[0,1,2]` is reused for all 3 rows, and each row of `a` gets `[0,1,2]` added — giving `[[5,6,7],[5,6,7],[5,6,7]]`. 🎯

The only changes: **Rule 3's explanation, the Rule 3 lines in both full traces, and the Rule 3 row in the plain-English table and summary** — all now compare each input against the **output** shape. Rules 1, 2, and 4 are untouched. 🎯

In [6]:
a=np.array([1,2,3])
b=np.array([4,5])
try:
    a+b
except ValueError as e:
    import sys
    print(e,file=sys.stderr)



operands could not be broadcast together with shapes (3,) (2,) 
