<img src = 'images/image2.png' width=600>

In [1]:
import numpy as np

In [7]:
x=np.array([
    [0,1,2,3]
])
print(a)
y=a.T

[[0 1 2 3]]


In [8]:
c=x*y
print(c)

[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]


In [17]:
def multiplication_table(n):
    x=np.arange(n).reshape(1,n)
    y=x.T
    print(x*y)

In [18]:
multiplication_table(4)

[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]
